version: "3.9"
name: demo

services:
  mongodb:
    image: mongo:jammy
    container_name: mongo-demo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: test
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      timeout: 5s
      retries: 20

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-demo
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672

networks:
  default:
    driver: bridge

volumes:
  mongodbdata:
